services:
  db:
    image: postgres:13-alpine
    container_name: aml_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: aml_redis
    restart: unless-stopped

  backend:
    build: .
    container_name: aml_django_backend
    command: gunicorn aml.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
 
volumes:
  postgres_data: