# Generated by Django 5.2.6 on 2025-09-30 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(db_index=True, help_text="So'rov yuborilgan API nomi (masalan, 'notary', 'tax')", max_length=100, verbose_name='API nomi')),
                ('request_payload', models.JSONField(help_text="Tashqi API'ga yuborilgan ma'lumotlar", verbose_name="So'rov tanasi (Request Payload)")),
                ('response_data', models.JSONField(blank=True, help_text="Tashqi API'dan qaytgan javob", null=True, verbose_name='Javob tanasi (Response Data)')),
                ('status_code', models.PositiveIntegerField(blank=True, help_text="So'rovning HTTP statusi (masalan, 200)", null=True, verbose_name='HTTP Status Kodi')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="So'rov jo'natilgan vaqt", verbose_name='Yaratilgan vaqti')),
                ('user', models.ForeignKey(blank=True, help_text="So'rovni yuborgan tizim foydalanuvchisi (agar mavjud bo'lsa)", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "API So'rov Logi",
                'verbose_name_plural': "API So'rovlari Loglari",
                'db_table': 'shared_api_action_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
