# Generated by Django 5.2.6 on 2025-09-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logging_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate', models.DateField(blank=True, help_text="Notarial harakatning ro'yxatga olingan sanasi", null=True, verbose_name='Дата реестра')),
                ('regnum', models.CharField(blank=True, help_text='Notarial harakatning reyestr raqami', max_length=50, null=True, verbose_name='Номер реестра')),
                ('office', models.CharField(blank=True, help_text='Notarial idora nomi', max_length=255, null=True, verbose_name='Наименование нот.конторы')),
                ('notary_code', models.CharField(blank=True, help_text='Notariusning litsenziya kodi', max_length=10, null=True, verbose_name='Код нотариуса')),
                ('notary_fio', models.CharField(blank=True, help_text='Notariusning F.I.Sh.', max_length=255, null=True, verbose_name='ФИО нотариуса')),
                ('type', models.CharField(blank=True, help_text='Notarial harakat turi', max_length=255, null=True, verbose_name='Тип нот.действия')),
                ('state', models.CharField(blank=True, help_text="Notarial harakat holati (masalan, 'Ro'yxatga olingan')", max_length=100, null=True, verbose_name='Состояние нот.действия')),
                ('relative', models.IntegerField(blank=True, help_text='Qarindoshlik aloqalari (1-boshqa shaxslar, 2-qarindoshlar)', null=True, verbose_name='Родственные связи')),
                ('term_from', models.DateField(blank=True, help_text='Ijara boshlanish sanasi', null=True, verbose_name='Дата начала аренды')),
                ('term_to', models.DateField(blank=True, help_text='Ijara tugash sanasi', null=True, verbose_name='Дата конца аренды')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, help_text='Bir oylik ijara summasi', max_digits=20, null=True, verbose_name='Сумма за один месяц аренды')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, help_text='Ijarani umumiy summasi', max_digits=20, null=True, verbose_name='Общая сумма аренды')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notary_registry_data', to='logging_module.apiactionlog', verbose_name='API Log Zapisi')),
            ],
            options={
                'verbose_name': 'Данные реестра',
                'verbose_name_plural': 'Данные реестров',
                'db_table': 'notary_registry_data',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, help_text="Ishtirokchi turi (masalan, 'sotuvchi')", max_length=100, null=True, verbose_name='Тип участника')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, help_text='Ismi yoki tashkilot nomi', max_length=255, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('inn', models.CharField(blank=True, max_length=9, null=True, verbose_name='ИНН')),
                ('pin', models.CharField(blank=True, max_length=14, null=True, verbose_name='ПИНФЛ')),
                ('pass_serial', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия паспорта')),
                ('pass_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('represent_to', models.CharField(blank=True, help_text="Kimning nomidan ish ko'rayotgani", max_length=255, null=True, verbose_name='Представляет интересы')),
                ('registry_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='justice.registrydata', verbose_name='Запись реестра')),
            ],
            options={
                'verbose_name': 'Участник действия',
                'verbose_name_plural': 'Участники действия',
                'db_table': 'notary_member',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, help_text="Obyekt turi (masalan, 'Yengil avtomobil')", max_length=100, null=True, verbose_name='Тип объекта')),
                ('cadastrenum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кадастровый номер')),
                ('mark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка/модель')),
                ('regnum', models.CharField(blank=True, max_length=20, null=True, verbose_name='Гос. номер')),
                ('yearcreate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('techserial', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия тех. паспорта')),
                ('technum', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер тех. паспорта')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Стоимость')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес объекта')),
                ('quadrature', models.FloatField(blank=True, null=True, verbose_name='Площадь (кв.м.)')),
                ('registry_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='justice.registrydata', verbose_name='Запись реестра')),
            ],
            options={
                'verbose_name': 'Объект действия',
                'verbose_name_plural': 'Объекты действия',
                'db_table': 'notary_subject',
            },
        ),
    ]
