# Generated by Django 5.2.6 on 2025-10-02 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.BigIntegerField(db_index=True, help_text='DPM tizimidagi unikal ID', unique=True)),
                ('photo_id', models.BigIntegerField(blank=True, help_text='DPM tizimidagi rasm IDsi', null=True)),
                ('pinpp', models.CharField(db_index=True, help_text='JSHSHIR', max_length=14, unique=True)),
                ('surname_latin', models.CharField(max_length=100)),
                ('name_latin', models.CharField(max_length=100)),
                ('patronym_latin', models.CharField(blank=True, max_length=100, null=True)),
                ('surname_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('patronym_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_seria', models.CharField(blank=True, max_length=10, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_start_date', models.DateField(blank=True, null=True)),
                ('doc_end_date', models.DateField(blank=True, null=True)),
                ('doc_give_place', models.CharField(blank=True, max_length=255, null=True)),
                ('is_doc_active', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('sex_id', models.IntegerField(blank=True, help_text='1-Erkak, 2-Ayol', null=True)),
                ('nationality_name', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('living_country', models.CharField(blank=True, max_length=100, null=True)),
                ('living_region', models.CharField(blank=True, max_length=100, null=True)),
                ('living_district', models.CharField(blank=True, max_length=100, null=True)),
                ('living_place', models.CharField(blank=True, max_length=255, null=True)),
                ('living_address_full', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorderCrossing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_type', models.CharField(help_text='P-kirish; M-chiqish', max_length=50)),
                ('reg_date', models.DateTimeField(help_text='Chegara kesish sanasi va vaqti')),
                ('direction_country', models.CharField(max_length=100)),
                ('trip_purpose_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_crossings', to='dpm.person')),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type_name', models.CharField(help_text='Qarindoshlik turi (ota, ona, farzand)', max_length=100)),
                ('relative_person_id', models.BigIntegerField()),
                ('pinpp', models.CharField(db_index=True, max_length=14)),
                ('surname_latin', models.CharField(max_length=100)),
                ('name_latin', models.CharField(max_length=100)),
                ('patronym_latin', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='dpm.person')),
            ],
        ),
    ]
