# Generated by Django 5.2.6 on 2025-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Shaxsning rasmi', null=True, upload_to='photos/'),
        ),
    ]
